version: '{branch}-{build}'

init:
  # Create our AppVeyor version
  - ps: $env:commit = $env:appveyor_repo_commit.SubString(0,7)
  - ps: Update-AppveyorBuild -Version ("{0}-{1}-{2}" -f $env:appveyor_repo_branch,$env:appveyor_build_number,$env:commit )

os: Visual Studio 2019

environment:
  matrix:
    - MSVC_VERSION: 19
      RUNTIME_LINKAGE: static
      QT_VERSION: 5.15
      QT_LINKAGE: static
      COVERITY_BUILD_CANDIDATE: True
      #https://www.appveyor.com/docs/build-environment/#qt
      QTDIR: C:\Qt\%QT_VERSION%\msvc2019_64
      PRJLIBS: VCRUNTIME140.dll MSVCP140.dll ucrtbased.dll

configuration:
  - release
  - debug

install:
  # Set and load necessary variables
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake -v
  - set PRJLIBDIR=%WINDIR%\SysWOW64 # Find vclibss
  - set QTDIR
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
  - set BIN=mini-qml

before_build:
  # Prepare the out-of-source build directory.
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir %APPVEYOR_BUILD_FOLDER%-build
  - qmake -o %APPVEYOR_BUILD_FOLDER%-build -r -Wall -Wlogic -Wparser CONFIG+=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%

build_script:
  # Compile it and check for .exe
  - cd %APPVEYOR_BUILD_FOLDER%-build
  - nmake
  - dir /b /s *.exe

after_build:
  # Add a link to the build output within the source directory. This is needed because AppVeyor does
  # not support extracting artifacts from out-of-source build directories. See 'artifacts' below.
  - dir /b /s *.exe
  - mkdir deploy
  - copy %APPVEYOR_BUILD_FOLDER%-build\%CONFIGURATION%\%BIN%.exe deploy\%BIN%.exe
  - windeployqt --qmldir %APPVEYOR_BUILD_FOLDER%/qml --%CONFIGURATION% deploy/%BIN%.exe --verbose=2
  - for %%I in (%PRJLIBS%) do copy %PRJLIBDIR%\%%I deploy\
  - 7z a -tzip %BIN%_%CONFIGURATION%.zip deploy -r
  - copy %APPVEYOR_BUILD_FOLDER%-build\%BIN%_%CONFIGURATION%.zip %APPVEYOR_BUILD_FOLDER%\%BIN%_%CONFIGURATION%.zip
  - dir /b /s *.zip

artifacts:
  - path: '%BIN%_%CONFIGURATION%.zip'
    name: '%BIN%'

deploy:
  - provider: GitHub
    on:
      branch: master
    release: continuous
    artifact: '%BIN%'
    draft: false
    prerelease: true
    auth_token:
      secure: BC8BBwf6sV+/f+AoRHCskXQBXwdvXuXB7sFuJWN0lbIzJs8E87T77aY5HovyaFmc